version: "3.9"

services:
  database:
    container_name: mongo
    image: "bitnami/mongodb:latest"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=prisma
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
    volumes:
      - "mongo-db:/bitnami/mongodb"

  server:
    container_name: graphql_backend
    build:
      context: ./backend
    volumes:
      - "./backend:/backend"
    ports:
      - "4000:4000"
      - "5000:5555"
    depends_on:
      - mongo
    restart: always

  client:
    container_name: nextjs_frontend
    build:
      context: ./frontend
    volumes:
      - "./frontend:/frontend"
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always

volumes:
  mongo-db:
  server:
  client:
